import {
  LayoutDashboard,
  Users,
  Building2,
  Factory,
  FolderCheck,
  ShieldCheck,
  HelpCircle,
  FileEdit,
  CalendarCheck,
  Calendar,
  ClipboardList,
  SearchCheck,
  AlertTriangle,
  Wrench,
  Camera,
  BarChart3,
  ThumbsUp,
  Settings,
  ClipboardCheck,
  BookOpen,
} from "lucide-react";

export const navItems = {
  superAdmin: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/superAdmin",
    },
    {
      id: "users",
      label: "Users",
      icon: Users,
      href: "/dashboard/superAdmin/users",
    },
    {
      id: "groups",
      label: "Groups",
      icon: Building2,
      href: "/dashboard/superAdmin/groups",
    },
    {
      id: "companies",
      label: "Companies",
      icon: Building2,
      href: "/dashboard/superAdmin/companies",
    },
    {
      id: "sites",
      label: "Sites",
      icon: Factory,
      href: "/dashboard/superAdmin/sites",
    },
    {
      id: "check-types",
      label: "Categories",
      icon: FolderCheck,
      href: "/dashboard/superAdmin/check-types",
    },
    {
      id: "rules",
      label: "Rules",
      icon: ShieldCheck,
      href: "/dashboard/superAdmin/rules",
    },
    {
      id: "questions",
      label: "Questions",
      icon: HelpCircle,
      href: "/dashboard/superAdmin/questions",
    },
    {
      id: "templates",
      label: "Templates",
      icon: FileEdit,
      href: "/dashboard/superAdmin/templates",
    },
    {
      id: "programs",
      label: "Programs",
      icon: CalendarCheck,
      href: "/dashboard/superAdmin/programs",
    },
    {
      id: "schedules",
      label: "Schedules",
      icon: Calendar,
      href: "/dashboard/superAdmin/schedules",
    },
    {
      id: "auditSessions",
      label: "Audit Sessions",
      icon: ClipboardList,
      href: "/dashboard/superAdmin/auditsessions",
    },
    {
      id: "teams",
      label: "Teams",
      icon: Users,
      href: "/dashboard/superAdmin/teams",
    },
    {
      id: "observations",
      label: "Observations",
      icon: SearchCheck,
      href: "/dashboard/superAdmin/observations",
    },
    {
      id: "problems",
      label: "Problems",
      icon: AlertTriangle,
      href: "/dashboard/superAdmin/problems",
    },
    {
      id: "fix-actions",
      label: "Fix Actions",
      icon: Wrench,
      href: "/dashboard/superAdmin/fix-actions",
    },
    {
      id: "proofs",
      label: "Proofs",
      icon: Camera,
      href: "/dashboard/superAdmin/proofs",
    },
    {
      id: "reports",
      label: "Reports",
      icon: BarChart3,
      href: "/dashboard/superAdmin/reports",
    },
    {
      id: "approvals",
      label: "Approvals",
      icon: ThumbsUp,
      href: "/dashboard/superAdmin/approvals",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/superAdmin/settings",
    },
  ],

  groupAdmin: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/groupAdmin",
    },
    {
      id: "users",
      label: "Users",
      icon: Users,
      href: "/dashboard/groupAdmin/users",
    },
    {
      id: "companies",
      label: "Companies",
      icon: Building2,
      href: "/dashboard/groupAdmin/companies",
    },
    {
      id: "sites",
      label: "Sites",
      icon: Factory,
      href: "/dashboard/groupAdmin/sites",
    },
    {
      id: "problems",
      label: "Problems",
      icon: AlertTriangle,
      href: "/dashboard/groupAdmin/problems",
    },
    {
      id: "fix-actions",
      label: "Fix Actions",
      icon: Wrench,
      href: "/dashboard/groupAdmin/fix-actions",
    },
    {
      id: "reports",
      label: "Reports",
      icon: BarChart3,
      href: "/dashboard/groupAdmin/reports",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/groupAdmin/settings",
    },
  ],

  companyAdmin: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/companyAdmin",
    },
    {
      id: "users",
      label: "Users",
      icon: Users,
      href: "/dashboard/companyAdmin/users",
    },
    {
      id: "sites",
      label: "Sites",
      icon: Factory,
      href: "/dashboard/companyAdmin/sites",
    },
    {
      id: "schedules",
      label: "Schedules",
      icon: Calendar,
      href: "/dashboard/companyAdmin/schedules",
    },
    {
      id: "auditSessions",
      label: "Audit Sessions",
      icon: ClipboardList,
      href: "/dashboard/companyAdmin/auditsessions",
    },
    {
      id: "fix-actions",
      label: "Fix Actions",
      icon: Wrench,
      href: "/dashboard/companyAdmin/fix-actions",
    },
    {
      id: "reports",
      label: "Reports",
      icon: BarChart3,
      href: "/dashboard/companyAdmin/reports",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/companyAdmin/settings",
    },
  ],

  complianceOfficer: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/complianceOfficer",
    },
    {
      id: "library",
      label: "Standards Library",
      icon: BookOpen,
      submenu: [
        {
          id: "checkTypes",
          label: "Check Types",
          href: "/dashboard/complianceOfficer/check-types",
        },
        {
          id: "rules",
          label: "Rules",
          href: "/dashboard/complianceOfficer/rules",
        },
        {
          id: "questions",
          label: "Questions",
          href: "/dashboard/complianceOfficer/questions",
        },
        {
          id: "templates",
          label: "Templates",
          href: "/dashboard/complianceOfficer/templates",
        },
      ],
    },
    {
      id: "programs",
      label: "Programs",
      icon: CalendarCheck,
      href: "/dashboard/complianceOfficer/programs",
    },
    {
      id: "approvals",
      label: "Approvals",
      icon: ThumbsUp,
      href: "/dashboard/complianceOfficer/approvals",
    },
    {
      id: "reports",
      label: "Reports",
      icon: BarChart3,
      href: "/dashboard/complianceOfficer/reports",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/complianceOfficer/settings",
    },
  ],

  auditor: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/auditor",
    },
    {
      id: "assignments",
      label: "My Assignments",
      icon: Calendar,
      href: "/dashboard/auditor/schedules",
    },
    {
      id: "auditSessions",
      label: "Active Audits",
      icon: ClipboardList,
      href: "/dashboard/auditor/auditsessions",
    },
    {
      id: "observations",
      label: "Observations",
      icon: SearchCheck,
      href: "/dashboard/auditor/observations",
    },
    {
      id: "proofs",
      label: "Proofs",
      icon: Camera,
      href: "/dashboard/auditor/proofs",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/auditor/settings",
    },
  ],

  siteManager: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/siteManager",
    },
    {
      id: "problems",
      label: "My Problems",
      icon: ClipboardList,
      href: "/dashboard/siteManager/problems",
    },
    {
      id: "fix-actions",
      label: "Fix Actions",
      icon: Wrench,
      href: "/dashboard/siteManager/fix-actions",
    },
    {
      id: "proofs",
      label: "Proofs",
      icon: Camera,
      href: "/dashboard/siteManager/proofs",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/siteManager/settings",
    },
  ],

  problemOwner: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/problemOwner",
    },
    {
      id: "my-tasks",
      label: "My Tasks",
      icon: ClipboardList,
      href: "/dashboard/problemOwner/my-problems",
    },
    {
      id: "fix-actions",
      label: "Fix Actions",
      icon: Wrench,
      href: "/dashboard/problemOwner/fix-actions",
    },
    {
      id: "proofs",
      label: "Proofs",
      icon: Camera,
      href: "/dashboard/problemOwner/proofs",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/problemOwner/settings",
    },
  ],

  approver: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/approver",
    },
    {
      id: "pending-approvals",
      label: "Approvals",
      icon: ClipboardCheck,
      href: "/dashboard/approver/approvals",
    },
    {
      id: "reports",
      label: "Reports",
      icon: BarChart3,
      href: "/dashboard/approver/reports",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/approver/settings",
    },
  ],
};
