import {
  LayoutDashboard,
  Users,
  Building2,
  Factory,
  FolderCheck,
  ShieldCheck,
  HelpCircle,
  FileEdit,
  CalendarCheck,
  Calendar,
  ClipboardList,
  SearchCheck,
  AlertTriangle,
  Wrench,
  Camera,
  BarChart3,
  ThumbsUp,
  Settings,
} from "lucide-react";

export const navItems = {
  sysadmin: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/sysadmin",
    },
    {
      id: "users",
      label: "Users",
      icon: Users,
      href: "/dashboard/sysadmin/users",
    },
    {
      id: "groups",
      label: "Groups",
      icon: Building2,
      href: "/dashboard/sysadmin/groups",
    },
    {
      id: "companies",
      label: "Companies",
      icon: Building2,
      href: "/dashboard/sysadmin/companies",
    },
    {
      id: "sites",
      label: "Sites",
      icon: Factory,
      href: "/dashboard/sysadmin/sites",
    },
    {
      id: "check-types",
      label: "Categories",
      icon: FolderCheck,
      href: "/dashboard/sysadmin/check-types",
    },
    {
      id: "rules",
      label: "Rules",
      icon: ShieldCheck,
      href: "/dashboard/sysadmin/rules",
    },
    {
      id: "questions",
      label: "Questions",
      icon: HelpCircle,
      href: "/dashboard/sysadmin/questions",
    },
    {
      id: "templates",
      label: "Templates",
      icon: FileEdit,
      href: "/dashboard/sysadmin/templates",
    },
    {
      id: "programs",
      label: "Programs",
      icon: CalendarCheck,
      href: "/dashboard/sysadmin/programs",
    },
    {
      id: "schedules",
      label: "Schedules",
      icon: Calendar,
      href: "/dashboard/sysadmin/schedules",
    },
    {
      id: "auditSessions",
      label: "Audit Sessions",
      icon: ClipboardList,
      href: "/dashboard/sysadmin/auditsessions",
    },
    {
      id: "teams",
      label: "Teams",
      icon: Users,
      href: "/dashboard/sysadmin/teams",
    },
    {
      id: "observations",
      label: "Observations",
      icon: SearchCheck,
      href: "/dashboard/sysadmin/observations",
    },
    {
      id: "problems",
      label: "Problems",
      icon: AlertTriangle,
      href: "/dashboard/sysadmin/problems",
    },
    {
      id: "fix-actions",
      label: "Fix Actions",
      icon: Wrench,
      href: "/dashboard/sysadmin/fix-actions",
    },
    {
      id: "proofs",
      label: "Proofs",
      icon: Camera,
      href: "/dashboard/sysadmin/proofs",
    },
    {
      id: "reports",
      label: "Reports",
      icon: BarChart3,
      href: "/dashboard/sysadmin/reports",
    },
    {
      id: "approvals",
      label: "Approvals",
      icon: ThumbsUp,
      href: "/dashboard/sysadmin/approvals",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/sysadmin/settings",
    },
  ],

  admin: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/admin",
    },
    {
      id: "users",
      label: "Users",
      icon: Users,
      href: "/dashboard/admin/users",
    },
    {
      id: "companies",
      label: "Companies",
      icon: Building2,
      href: "/dashboard/admin/companies",
    },
    {
      id: "sites",
      label: "Sites",
      icon: Factory,
      href: "/dashboard/admin/sites",
    },
    {
      id: "check-types",
      label: "Categories",
      icon: FolderCheck,
      href: "/dashboard/admin/check-types",
    },
    {
      id: "rules",
      label: "Rules",
      icon: ShieldCheck,
      href: "/dashboard/admin/rules",
    },
    {
      id: "questions",
      label: "Questions",
      icon: HelpCircle,
      href: "/dashboard/admin/questions",
    },
    {
      id: "templates",
      label: "Templates",
      icon: FileEdit,
      href: "/dashboard/admin/templates",
    },
    {
      id: "programs",
      label: "Programs",
      icon: CalendarCheck,
      href: "/dashboard/admin/programs",
    },
    {
      id: "schedules",
      label: "Schedules",
      icon: Calendar,
      href: "/dashboard/admin/schedules",
    },
    {
      id: "auditSessions",
      label: "Audit Sessions",
      icon: ClipboardList,
      href: "/dashboard/admin/auditsessions",
    },
    {
      id: "teams",
      label: "Teams",
      icon: Users,
      href: "/dashboard/admin/teams",
    },
    {
      id: "observations",
      label: "Observations",
      icon: SearchCheck,
      href: "/dashboard/admin/observations",
    },
    {
      id: "problems",
      label: "Problems",
      icon: AlertTriangle,
      href: "/dashboard/admin/problems",
    },
    {
      id: "fix-actions",
      label: "Fix Actions",
      icon: Wrench,
      href: "/dashboard/admin/fix-actions",
    },
    {
      id: "proofs",
      label: "Proofs",
      icon: Camera,
      href: "/dashboard/admin/proofs",
    },
    {
      id: "reports",
      label: "Reports",
      icon: BarChart3,
      href: "/dashboard/admin/reports",
    },
    {
      id: "approvals",
      label: "Approvals",
      icon: ThumbsUp,
      href: "/dashboard/admin/approvals",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/admin/settings",
    },
  ],

  compliance_officer: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/compliance",
    },
    {
      id: "check-types",
      label: "Categories",
      icon: FolderCheck,
      href: "/dashboard/compliance/check-types",
    },
    {
      id: "rules",
      label: "Rules",
      icon: ShieldCheck,
      href: "/dashboard/compliance/rules",
    },
    {
      id: "questions",
      label: "Questions",
      icon: HelpCircle,
      href: "/dashboard/compliance/questions",
    },
    {
      id: "templates",
      label: "Templates",
      icon: FileEdit,
      href: "/dashboard/compliance/templates",
    },
    {
      id: "programs",
      label: "Programs",
      icon: CalendarCheck,
      href: "/dashboard/compliance/programs",
    },
    {
      id: "reports",
      label: "Reports",
      icon: BarChart3,
      href: "/dashboard/compliance/reports",
    },
    {
      id: "approvals",
      label: "Approvals",
      icon: ThumbsUp,
      href: "/dashboard/compliance/approvals",
    },
    {
      id: "observations",
      label: "Observations",
      icon: SearchCheck,
      href: "/dashboard/compliance/observations",
    },
    {
      id: "problems",
      label: "Problems",
      icon: AlertTriangle,
      href: "/dashboard/compliance/problems",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/complianceOfficer/settings",
    },
  ],

  manager: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/manager",
    },
    {
      id: "users",
      label: "Users",
      icon: Users,
      href: "/dashboard/manager/users",
    },
    {
      id: "schedules",
      label: "Schedules",
      icon: Calendar,
      href: "/dashboard/manager/schedules",
    },
    {
      id: "auditSessions",
      label: "Audit Sessions",
      icon: ClipboardList,
      href: "/dashboard/manager/auditsessions",
    },
    {
      id: "teams",
      label: "Teams",
      icon: Users,
      href: "/dashboard/manager/teams",
    },
    {
      id: "observations",
      label: "Observations",
      icon: SearchCheck,
      href: "/dashboard/manager/observations",
    },
    {
      id: "problems",
      label: "Problems",
      icon: AlertTriangle,
      href: "/dashboard/manager/problems",
    },
    {
      id: "fix-actions",
      label: "Fix Actions",
      icon: Wrench,
      href: "/dashboard/manager/fix-actions",
    },
    {
      id: "proofs",
      label: "Proofs",
      icon: Camera,
      href: "/dashboard/manager/proofs",
    },
    {
      id: "reports",
      label: "Reports",
      icon: BarChart3,
      href: "/dashboard/manager/reports",
    },
    {
      id: "approvals",
      label: "Approvals",
      icon: ThumbsUp,
      href: "/dashboard/manager/approvals",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/manager/settings",
    },
  ],

  auditor: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      href: "/dashboard/auditor",
    },
    {
      id: "auditSessions",
      label: "Audit Sessions",
      icon: ClipboardList,
      href: "/dashboard/auditor/auditsessions",
    },
    {
      id: "observations",
      label: "Observations",
      icon: SearchCheck,
      href: "/dashboard/auditor/observations",
    },
    {
      id: "problems",
      label: "Problems",
      icon: AlertTriangle,
      href: "/dashboard/auditor/problems",
    },
    {
      id: "fix-actions",
      label: "Fix Actions",
      icon: Wrench,
      href: "/dashboard/auditor/fix-actions",
    },
    {
      id: "proofs",
      label: "Proofs",
      icon: Camera,
      href: "/dashboard/auditor/proofs",
    },
    {
      id: "settings",
      label: "Settings",
      icon: Settings,
      href: "/dashboard/auditor/settings",
    },
  ],
};
