// src/hooks/useExcelExport.js

import { useState } from "react";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

/**
 * Custom hook for Excel export functionality using SheetJS
 * Generates multi-sheet workbooks with professional structure (Merges, Filters)
 */
export const useExcelExport = () => {
  const [isExporting, setIsExporting] = useState(false);

  /**
   * Export report data to Excel format
   * @param {Object} reportData - The report object from backend
   * @param {String} filename - Custom filename (optional)
   */
  const exportToExcel = async (reportData, filename) => {
    if (!reportData) {
      console.error("No report data provided for Excel export");
      return;
    }

    try {
      setIsExporting(true);

      // Create new workbook
      const workbook = XLSX.utils.book_new();

      // --- Sheet 1: Report Summary ---
      const summarySheet = createSummarySheet(reportData);
      XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");

      // --- Sheet 2: Detailed Findings ---
      if (reportData.findings && reportData.findings.length > 0) {
        const findingsSheet = createFindingsSheet(reportData.findings);
        XLSX.utils.book_append_sheet(workbook, findingsSheet, "Findings");
      }

      // --- Sheet 3: Risk Analysis ---
      if (reportData.metrics) {
        const riskSheet = createRiskAnalysisSheet(reportData.metrics);
        XLSX.utils.book_append_sheet(workbook, riskSheet, "Risk Analysis");
      }

      // --- Sheet 4: Site Information ---
      if (reportData.auditSession) {
        const siteSheet = createSiteInfoSheet(reportData.auditSession);
        XLSX.utils.book_append_sheet(workbook, siteSheet, "Site Information");
      }

      // Generate Excel file
      const excelBuffer = XLSX.write(workbook, {
        bookType: "xlsx",
        type: "array",
      });

      // Create Blob and trigger download
      const blob = new Blob([excelBuffer], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      });

      const finalFilename =
        filename ||
        `${reportData.title?.replace(/[^a-z0-9]/gi, "_")}_report.xlsx`;
      saveAs(blob, finalFilename);

      console.log("✅ Excel export successful");
    } catch (error) {
      console.error("❌ Excel export failed:", error);
      throw error;
    } finally {
      setIsExporting(false);
    }
  };

  return { exportToExcel, isExporting };
};

/**
 * Create Summary Sheet with Merges
 */
function createSummarySheet(report) {
  // Data Grid
  const data = [
    ["AUDIT REPORT SUMMARY", "", "", ""], // Row 0: Title
    ["", "", "", ""], // Row 1: Spacer
    ["REPORT DETAILS", "", "KEY METRICS", ""], // Row 2: Headers
    [
      "Title",
      report.title || "N/A",
      "Total Findings",
      report.metrics?.totalProblems || 0,
    ],
    [
      "Type",
      report.reportType || "N/A",
      "Critical",
      report.metrics?.criticalProblems || 0,
    ],
    [
      "Status",
      report.reportStatus || "N/A",
      "High Risk",
      report.metrics?.highRiskProblems || 0,
    ],
    [
      "Generated By",
      report.generatedBy?.name || "N/A",
      "Medium Risk",
      report.metrics?.mediumRiskProblems || 0,
    ],
    [
      "Date",
      new Date(report.generatedAt).toLocaleDateString(),
      "Low Risk",
      report.metrics?.lowRiskProblems || 0,
    ],
    [
      "",
      "",
      "Overall Rating",
      (report.metrics?.overallRiskRating || "N/A").toUpperCase(),
    ],
    ["", "", "", ""],
    ["EXECUTIVE SUMMARY", "", "", ""], // Row 10
    [report.executiveSummary || "No summary available", "", "", ""],
  ];

  const ws = XLSX.utils.aoa_to_sheet(data);

  // Column Widths
  ws["!cols"] = [
    { wch: 20 }, // A: Label
    { wch: 40 }, // B: Value
    { wch: 20 }, // C: Label
    { wch: 15 }, // D: Value
  ];

  // Merges
  ws["!merges"] = [
    { s: { r: 0, c: 0 }, e: { r: 0, c: 3 } }, // Title across A-D
    { s: { r: 10, c: 0 }, e: { r: 10, c: 3 } }, // "Executive Summary" Header
    { s: { r: 11, c: 0 }, e: { r: 12, c: 3 } }, // Summary Body (spanning 2 rows for visual weight, though wrapped text depends on excel)
    // Merge headers if needed? No, separate columns is better.
  ];

  return ws;
}

/**
 * Create Findings Sheet with AutoFilter
 */
function createFindingsSheet(findings) {
  const headers = [
    "#",
    "Risk Level",
    "Description",
    "Recommendation",
    "Problem ID",
  ];
  const data = [
    ["DETAILED FINDINGS", "", "", "", ""], // Row 0
    headers, // Row 1: Headers
  ];

  findings.forEach((finding, index) => {
    data.push([
      index + 1,
      (finding.riskLevel || "medium").toUpperCase(),
      finding.description || "No description",
      finding.recommendation || "No recommendation",
      finding.problem?._id || finding.problem || "N/A",
    ]);
  });

  const ws = XLSX.utils.aoa_to_sheet(data);

  // Column Widths
  ws["!cols"] = [
    { wch: 5 }, // #
    { wch: 12 }, // Risk
    { wch: 60 }, // Desc
    { wch: 60 }, // Rec
    { wch: 25 }, // ID
  ];

  // Merges for Title
  ws["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 4 } }];

  // AutoFilter for Headers
  // Range: A2:E(end)
  const lastRow = data.length - 1;
  ws["!autofilter"] = { ref: `A2:E${lastRow + 1}` };

  return ws;
}

/**
 * Create Risk Analysis Sheet
 */
function createRiskAnalysisSheet(metrics) {
  const data = [
    ["RISK ANALYSIS DASHBOARD", "", ""],
    ["", "", ""],
    ["Risk Level", "Count", "Percentage"],
  ];

  const total = metrics.totalProblems || 1;
  const risks = [
    ["Critical", metrics.criticalProblems || 0],
    ["High", metrics.highRiskProblems || 0],
    ["Medium", metrics.mediumRiskProblems || 0],
    ["Low", metrics.lowRiskProblems || 0],
  ];

  risks.forEach(([level, count]) => {
    const pct = ((count / total) * 100).toFixed(1) + "%";
    data.push([level, count, pct]);
  });

  // Total Row
  data.push(["TOTAL", metrics.totalProblems || 0, "100%"]);

  const ws = XLSX.utils.aoa_to_sheet(data);

  ws["!cols"] = [{ wch: 20 }, { wch: 10 }, { wch: 15 }];
  ws["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 2 } }];

  return ws;
}

/**
 * Create Site Info Sheet
 */
function createSiteInfoSheet(session) {
  const data = [
    ["SITE AUDIT INFORMATION", ""],
    [],
    ["Field", "Value"],
    ["Audit Session", session.title || "N/A"],
    ["Site Name", session.site?.name || "N/A"],
    ["Location", session.site?.location || "N/A"],
    ["Company", session.company?.name || "N/A"],
    ["Template", session.template?.title || "N/A"],
    [
      "Date",
      session.scheduledDate
        ? new Date(session.scheduledDate).toLocaleDateString()
        : "N/A",
    ],
  ];

  const ws = XLSX.utils.aoa_to_sheet(data);
  ws["!cols"] = [{ wch: 25 }, { wch: 50 }];
  ws["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 1 } }];

  return ws;
}

export default useExcelExport;
